version: '3.10'

services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    # connect with host: postgres, port: 5432
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
       - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
       - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "3001:80"
volumes:
  postgres:
  pgadmin-data:
networks:
  default:
    name: shared-network
    external: true